### ISSUE TITLE
Add caching 

### ISSUE THREAD

**Issue by karansthr** [karansthr/Playlist-Length#9]
The result need to be stored on base of last modified date of directory,
example:
`playlistlen ~/Videos` -> gives x hours y minutes length content, then this result should be cache, and next time if someone run the command `playlistlen ~/Videos`  then cached result should be displayed instead of calculating length of media again if the last modified time of that directory is not changed

**Comment by ssaamm** [comment]
Where are you imagining this cache sitting? I would think in the home directory somewhere.

**Comment by karansthr** [comment]
home directory would work fine
